float GRAVEDAD = 10;
float m;
float m1;
float m2;
float inclinacion;
float friccion;
float tension;
float a;
float friccionc;
float peso;
float normal;
float masa;
float masa1;
float masa2;
float a2;
String msg1 = "Ingresa la masa que esta sobre el plano (g):";
String msg4 = "Ingresa la masa colgada:";
String msg2 = "Ingrese el grado de inclinación del plano:";
String msg3 = "Ingrese el coeficiente de fricción plano:";

void setup() {
  Serial.begin(9600);
}

void loop() {
    Serial.println("Bienvenido al módulo de dinámica, en el cual podrás realizar algunos ejercicios. By C.C");
    delay(100);
    Serial.println("Escoge el módelo del ejercio");
    delay(100);
    Serial.println("1 Plano inclinado sin polea");
    delay(200);
    Serial.println("2 Plano inclinado con polea en movimiento");
    while (!Serial.available());
    char tipo = Serial.read();
    if(tipo == '1'){
      Serial.println("Se ha selecionado Plano inclinado sin polea");
        Serial.end();
        Serial.begin(9600);
        Serial.print(msg1);
         while (!Serial.available());
           m = Serial.parseInt();
           masa = m/1000;
          Serial.print(masa,3);
          delay(500);
        Serial.println(msg2);
        Serial.end();
        Serial.begin(9600);
         while (!Serial.available());
         inclinacion = Serial.parseFloat();
        float incli= inclinacion * 0.01745;
        Serial.print(inclinacion);
        Serial.println();
        Serial.end();
        Serial.begin(9600);
      Serial.println("Friccion");
      Serial.println("a Cartulina/Cartón (0.504)");
      Serial.println("b Papel lija / Cartón (0.83)");
      Serial.println("c Tela/cartón (0.45)");
      Serial.println("d Acetato/ cartón (0.26)");
      Serial.println("e Madera / cartón (0.364)");
      Serial.print(msg3);
      while (!Serial.available());
      friccion = Serial.parseFloat();
      Serial.print(friccion);
      Serial.println();
      delay(1000);
      int peso = masa * GRAVEDAD;
      float normal = peso * cos(incli);
      float friccione = normal * friccion;
      float pesox = peso * sin(incli);
      Serial.println("Resultado:");
      Serial.println("Fuerzas en Y");
      Serial.print("Normal:");
                delay(500);
      Serial.print(normal);
      Serial.print("j N");
      Serial.println();
      delay(1000);
      Serial.print("Peso y:-");
      Serial.print(normal);
                delay(500);
      Serial.print("j N");
      Serial.println();
      delay(1000);
      Serial.println("Fuerzas en x");
      Serial.print("Peso x:");
                delay(500);
      Serial.print(pesox);
      Serial.print("i N");
      Serial.println();
      Serial.print("Fuerza de Friccion estatica:-");
                delay(500);
      Serial.print(friccione);
      Serial.print("i N");
      Serial.println();
      if(friccione >= pesox){
      Serial.print("Fuerza de Friccion real:-");
                delay(500);
      Serial.print(pesox);
      Serial.print("i N");
      Serial.println();
      Serial.println("El cuerpo esta en reposo");
      }
      if(friccione < pesox){
      Serial.print("Fuerza de Friccion real:-");
                delay(500);
      Serial.print(friccione);
      Serial.println("i N");
      Serial.println("El cuerpo esta en movimiento");
      delay(5000);
      }

      }
      if(tipo == '2'){
      Serial.println("Se ha seleccionado plano inclinado con polea");
      Serial.end();
        Serial.begin(9600);
        Serial.print(msg1);
         while (!Serial.available());
           m1 = Serial.parseInt();
           masa1 = m1/1000;
          Serial.print(masa1,3);
          delay(500);
        Serial.end();
        Serial.begin(9600);
        Serial.print(msg4);
         while (!Serial.available());
          m2 = Serial.parseInt();
          masa2 = m2/1000;
          Serial.print(masa2);
          delay(500);
        Serial.println(msg2);
        Serial.end();
        Serial.begin(9600);
         while (!Serial.available());
         inclinacion = Serial.parseFloat();
        float incli= inclinacion * 0.01745;
         Serial.end();
        Serial.begin(9600);
      Serial.println("Friccion");
      Serial.println("a Cartulina/Cartón (0.504)");
      Serial.println("b Papel lija / Cartón (0.83)");
      Serial.println("c Tela/cartón (0.45)");
      Serial.println("d Acetato/ cartón (0.26)");
      Serial.println("e Madera / cartón (0.364)");
      Serial.print(msg3);
      while (!Serial.available());
      friccionc = Serial.parseFloat();
      Serial.print(friccionc);
      Serial.println();
      delay(1000);
      int peso2 = masa2 * GRAVEDAD;

      int peso = masa1 * GRAVEDAD;
      float normal = peso * cos(incli);
      float friccionc = normal * friccion;
      float pesox = peso * sin(incli);
      float a = (pesox - peso2 - friccionc) / (masa1+masa2);
      if(a>0){
      float tension = peso2 + masa2 * a;
      Serial.println("Resultado: Cuerpo colgado");
      Serial.println("Fuerzas en Y");
      Serial.print("Tension:");
                delay(500);
      Serial.print(tension);
      Serial.print("j N");
      Serial.println();
      delay(1000);
      Serial.print("Peso:-");
      Serial.print(peso2);
                delay(500);
      Serial.print("j N");
      Serial.println();
      delay(1000);
      Serial.println("Resultado: Cuerpo sobre el plano");
      Serial.println("Fuerzas en Y");
      Serial.print("Normal:");
         delay(500);
      Serial.print(normal);
      Serial.print("j N");
      Serial.println();
      delay(1000);
      Serial.print("Peso y:-");
      Serial.print(normal);
        delay(500);
      Serial.print("j N");
      Serial.println();
      delay(1000);
      Serial.println("Fuerzas en x");
      Serial.print("Peso x:");
      Serial.print(pesox);
        delay(500);
      Serial.print("i N");
      Serial.println();
      delay(1000);
      Serial.print("Tension:-");
      Serial.print(tension);
        delay(500);
      Serial.print("i N");
      Serial.println();
      delay(1000);
      Serial.print("Fuerza de rozamiento cinético:-");
      Serial.print(friccionc);
      delay(500);
      Serial.print("i N");
      Serial.println();
      delay(1000);
      Serial.println("Aceleracion del sistema:");
      Serial.print(a);
      Serial.print("i m/s^2");
      }
      if(a<0){
      float a2 = (peso2 - pesox - friccionc) / (masa1+masa2);
      float tension = peso2 + masa2 * a;
      Serial.println("Resultado: Cuerpo colgado");
      Serial.println("Fuerzas en Y");
      Serial.print("Tension:-");
                delay(500);
      Serial.print(tension);
      Serial.print("j N");
      Serial.println();
      delay(1000);
      Serial.print("Peso:");
      Serial.print(peso2);
                delay(500);
      Serial.print("j N");
      Serial.println();
      delay(1000);
      Serial.println("Resultado: Cuerpo sobre el plano");
      Serial.println("Fuerzas en Y");
      Serial.print("Normal:");
         delay(500);
      Serial.print(normal);
      Serial.print("j N");
      Serial.println();
      delay(1000);
      Serial.print("Peso y:-");
      Serial.print(normal);
        delay(500);
      Serial.print("j N");
      Serial.println();
      delay(1000);
      Serial.println("Fuerzas en x");
      Serial.print("Peso x:-");
      Serial.print(pesox);
        delay(500);
      Serial.print("i N");
      Serial.println();
      delay(1000);
      Serial.print("Tension:+");
      Serial.print(tension);
        delay(500);
      Serial.print("i N");
      Serial.println();
      delay(1000);
      Serial.print("Fuerza de rozamiento cinético:-");
      Serial.print(friccionc);
      delay(500);
      Serial.print("i N");
      Serial.println();
      delay(1000);
      Serial.println("Aceleracion del sistema:");
      Serial.print(a2);
      Serial.print("i m/s^2");
      }
    }
    delay(5000);
    }